apiVersion: "v1"
kind: "List"
items:

- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      component: "kafka"
    name: "broker"
  spec:
    ports:
    - port: 9092
      targetPort: 9092
    selector:
      component: "broker"

- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      component: "broker"
    name: "kfk"
  spec:
    replicas: 1
    selector:
      component: "broker"
    template:
      metadata:
        labels:
          component: "broker"
      spec:
        serviceAccount: elasticsearch
        containers:
          - securityContext:
              runAsUser: 0
            env:
            - name: "KUBERNETES_TRUST_CERT"
              value: "true"
            - name: "ADVERTISED_PORT"
              value: "9092"
            - name: "EXHIBITOR_URL"
              value: "exhibitor.elk-test.svc.cluster.local"
            - name: "EXHIBITOR_PORT"
              value: "8181"
            image: "arrawatia/k8s-kafka-exhibitor:v3"
            imagePullPolicy: Always
            name: "broker-node"
            ports:
            - containerPort: 9092
              name: "broker-port"
