apiVersion: "v1"
kind: "List"
items:

- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      component: "zookeeper"
    name: "exhibitor"
  spec:
    ports:
    - port: 8181
      targetPort: 8181
    selector:
      component: "zookeeper"

- apiVersion: "v1"
  kind: "ReplicationController"
  metadata:
    labels:
      component: "zookeeper"
    name: "rc-zk"
  spec:
    replicas: 1
    selector:
      component: "zookeeper"
    template:
      metadata:
        labels:
          component: "zookeeper"
      spec:
        serviceAccount: elasticsearch
        containers:
          - securityContext:
              runAsUser: 0
            env:
            - name: "KUBERNETES_TRUST_CERT"
              value: "true"
            - name: "S3_BUCKET"
              value: "openshift-zk"
            - name: "S3_PREFIX"
              value: "zadd"
            - name: "AWS_ACCESS_KEY_ID"
              value: "xxxx"
            - name: "AWS_SECRET_ACCESS_KEY"
              value: "xxxxx"
            image: "arrawatia/zookeeper-exhibitor:latest"
            name: "zk-node"
            ports:
            - containerPort: 2181
              name: "client"
            - containerPort: 2888
              name: "followers"
            - containerPort: 3888
              name: "election"
